'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const split=s=>s.split(/[;\n]/).map(x=>x.trim()).filter(Boolean);
let config={schema_version:1,name:'',categories:[],domains:[],fields:[],domain_notes:[],context:{suppress_future:true,suppress_background:true,suppress_attribution:true,suppress_negation:true},reading_plan:{groups:[],reason_choices:[]}};
let token='',home='',step=0,browseTarget='',browseKind='folder',folder='',busy=false,handoffProject='';
async function api(path,data){const response=await fetch(path,{method:data?'POST':'GET',headers:{'X-Setup-Token':token,...(data?{'Content-Type':'application/json'}:{})},...(data?{body:JSON.stringify(data)}:{})});const value=await response.json();if(!response.ok)throw Error(value.error||'Request failed');return value;}
function error(e){$('#error').textContent=e.message||String(e);$('#error').hidden=false;$('#error').scrollIntoView({behavior:'smooth',block:'nearest'});}
function notice(s){$('#notice').textContent=s;$('#notice').hidden=!s;}
function cleanError(){$('#error').hidden=true;}
function slug(s){return s.toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'').slice(0,45)||'field';}
function nextId(prefix,items){let n=1;while(items.some(x=>x.id===prefix+'_'+n))n++;return prefix+'_'+n;}
function values(kind){return kind==='reading-groups'?config.reading_plan.groups:config[kind];}
function input(kind,index,key,label,value,area=false,help=''){return `<label>${label}${area?`<textarea data-kind="${kind}" data-index="${index}" data-key="${key}">${esc(Array.isArray(value)?value.join('\n'):value)}</textarea>`:`<input data-kind="${kind}" data-index="${index}" data-key="${key}" value="${esc(value)}">`}</label>${help?`<p class="hint">${help}</p>`:''}`;}
function check(kind,index,key,label,value){return `<label><input type="checkbox" data-kind="${kind}" data-index="${index}" data-key="${key}" ${value?'checked':''}>${label}</label>`;}
function typeInput(kind,index,value){return `<label>Answer format<select data-kind="${kind}" data-index="${index}" data-key="type">${[['single','Choose one'],['multi','Choose several'],['text','Free text']].map(([v,t])=>`<option value="${v}" ${value===v?'selected':''}>${t}</option>`).join('')}</select></label>`;}
function labelCards(kind){return config[kind].map((item,i)=>`<article class="card"><div class="section-head"><b>${kind==='categories'?'Category':'Domain'} ${i+1}</b><button data-remove="${kind}" data-index="${i}">Remove</button></div>${input(kind,i,'name','Label name',item.name)}${input(kind,i,'description','Definition / boundary',item.description,true)}<details><summary>Script matching terms · optional</summary>${input(kind,i,'terms','Matching words or phrases',item.terms,true,'One per line or separate with semicolons. A final * matches a word stem. Leave empty for manual assessment.')}${input(kind,i,'require_any','Also require at least one of these terms',item.require_any,true)}${input(kind,i,'exclude_terms','Suppress matches containing these terms',item.exclude_terms,true)}</details></article>`).join('')||'<p class="hint">No labels added yet.</p>';}
function fieldCards(kind){return config[kind].map((f,i)=>`<article class="card"><div class="section-head"><b>${kind==='fields'?'Field':'Note'} ${i+1}</b><button data-remove="${kind}" data-index="${i}">Remove</button></div><div class="grid">${input(kind,i,'title','Display title',f.title)}${kind==='fields'?input(kind,i,'group','Group heading',f.group):''}</div>${typeInput(kind,i,f.type||'text')}${f.type!=='text'?input(kind,i,'options','Answer choices',f.options||[],true,'One choice per line. Use your own short, clear options.'):''}${kind==='fields'?input(kind,i,'hint','Guidance shown while reviewing',f.hint||'',true):''}<div class="checks">${kind==='fields'?check(kind,i,'required','Required before confirmation',f.required)+check(kind,i,'author','Reviewer interpretation',f.author)+check(kind,i,'overview','Show in synthesis overview',!config.overview_fields||config.overview_fields.includes(f.id)):''}</div><details><summary>Advanced field settings</summary>${input(kind,i,'id','Stable field ID',f.id)}${f.type!=='text'?input(kind,i,'exclusive_options','Choices that must stand alone',f.exclusive_options||[],true):''}</details></article>`).join('')||'<p class="hint">No fields added yet.</p>';}
function readingCards(){return config.reading_plan.groups.map((g,i)=>`<article class="card"><div class="section-head"><b>Priority ${i+1}</b><div><button data-move="${i}" data-direction="-1" ${i===0?'disabled':''}>↑</button><button data-move="${i}" data-direction="1" ${i===config.reading_plan.groups.length-1?'disabled':''}>↓</button><button data-remove="reading-groups" data-index="${i}">Remove</button></div></div>${input('reading-groups',i,'title','Group title',g.title)}<label>Reading depth<select data-kind="reading-groups" data-index="${i}" data-key="depth"><option value="detailed" ${g.depth==='detailed'?'selected':''}>Detailed</option><option value="brief" ${g.depth==='brief'?'selected':''}>Brief check</option></select></label>${['decision_links','categories_any','categories_exact'].map(k=>input('reading-groups',i,k,({decision_links:'Match output / decision-link values from your CSV',categories_any:'Match any of these category labels',categories_exact:'Match exactly this set of category labels'})[k],g.match?.[k]||[],true)).join('')}<p class="hint">Leave all conditions empty to catch the remaining papers.</p></article>`).join('');}
function render(){for(const kind of ['categories','domains'])$('#'+kind).innerHTML=labelCards(kind);for(const kind of ['fields','domain_notes'])$('#'+kind).innerHTML=fieldCards(kind);$('#reading-groups').innerHTML=readingCards();$('#reading-reasons').value=(config.reading_plan.reason_choices||[]).join('\n');$('#context').innerHTML=Object.entries({suppress_future:'Future work',suppress_background:'Background passages',suppress_attribution:'Work attributed to other authors',suppress_negation:'Negative statements'}).map(([k,v])=>`<label><input type="checkbox" data-context="${k}" ${config.context?.[k]!==false?'checked':''}>Suppress ${v.toLowerCase()}</label>`).join('');$('#sections').innerHTML=(config.sections||[]).map((s,i)=>`<article class="card"><div class="section-head"><b>Section ${i+1}</b><button data-remove="sections" data-index="${i}">Remove</button></div>${input('sections',i,'id','Section ID',s.id)}${input('sections',i,'title','Title',s.title)}${input('sections',i,'headings','Recognised headings',s.headings,true)}</article>`).join('');updateSummary();}
function setStep(n){step=Math.max(0,Math.min(3,n));$$('[data-page]').forEach(e=>e.hidden=+e.dataset.page!==step);$$('[data-step]').forEach(e=>{e.classList.toggle('active',+e.dataset.step===step);e.setAttribute('aria-current',+e.dataset.step===step?'step':'false');});$('#back').hidden=step===0;$('#next').hidden=step===3;$('#step-count').textContent=`Step ${step+1} of 4`;updateSummary();}
function payload(){config.name=$('#project-name').value.trim();const name=$('#run-name').value.trim();if(!name||/[\\/:*?"<>|]/.test(name)||['.','..'].includes(name))throw Error('Choose a new review folder name without path separators.');const parent=$('#parent-folder').value.trim().replace(/[\\/]$/,'');return {config,csv:$('#csv').value.trim(),pdf_root:$('#pdf-root').value.trim(),out:parent+'/'+name,...(handoffProject?{project:handoffProject}:{})};}
function updateSummary(){$('#summary').innerHTML=`<p><b>Project:</b> ${esc($('#project-name').value||'Not named yet')}</p><p><b>Categories:</b> ${esc(config.categories.map(x=>x.name||'Unnamed').join(', ')||'None yet')}</p><p><b>Domains:</b> ${esc(config.domains.map(x=>x.name||'Unnamed').join(', ')||'None')}</p><p><b>Evidence form:</b> ${config.fields.length} fields · ${config.domain_notes.length} synthesis notes</p><p><b>Sources:</b> ${esc(handoffProject||$('#csv').value||'Select your CSV')}</p><p><b>New folder:</b> ${esc($('#parent-folder').value)}/${esc($('#run-name').value)}</p>`;}
function download(name,text,mime){const url=URL.createObjectURL(new Blob([text],{type:mime}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function browse(path){try{const data=await api('/api/browse?'+new URLSearchParams({path:path||home,kind:browseKind}));folder=data.path;$('#browse-path').value=folder;$('#browse-up').dataset.path=data.parent;$('#drive').innerHTML=data.drives.map(d=>`<option ${folder.toLowerCase().startsWith(d.toLowerCase())?'selected':''}>${esc(d)}</option>`).join('');$('#file-list').innerHTML=data.entries.map(e=>`<button data-file-path="${esc(e.path)}" data-directory="${e.directory}">${e.directory?'▸ ':''}${esc(e.name)}${e.directory?'/':''}</button>`).join('')||'<p class="hint">No matching files or folders.</p>';$('#browse-error').textContent='';}catch(e){$('#browse-error').textContent=e.message;}}
function choosePath(p){$('#'+browseTarget).value=p;$('#browser').close();updateSummary();}
async function poll(){try{const job=await api('/api/job');$('#progress-log').textContent=(job.log||[]).join('\n');if(job.status==='complete'){notice('Review ready. Opening the interface…');location.assign(job.url);return;}if(job.status==='error')throw Error(job.error);setTimeout(poll,800);}catch(e){busy=false;$('#create').disabled=false;$('#resume-go').disabled=false;error(e);$('#resume-error').textContent=e.message;}}
async function run(path,data){if(busy)return;cleanError();await api(path,data);busy=true;$('#create').disabled=true;$('#resume-go').disabled=true;$('#progress').hidden=false;$('#progress-message').textContent='Preparing your review locally. This can take a few minutes for many PDFs. Keep this page open.';poll();}
document.addEventListener('input',e=>{const d=e.target.dataset;if(d.kind){const item=values(d.kind)[+d.index],key=d.key,value=e.target.type==='checkbox'?e.target.checked:e.target.value;if(d.kind==='reading-groups'&&['decision_links','categories_any','categories_exact'].includes(key)){item.match??={};const list=split(value);if(list.length)item.match[key]=list;else delete item.match[key];}else if(key==='overview'){config.overview_fields??=config.fields.map(f=>f.id);config.overview_fields=value?[...new Set([...config.overview_fields,item.id])]:config.overview_fields.filter(id=>id!==item.id);}else{const old=item.id;item[key]=['terms','require_any','exclude_terms','options','exclusive_options','headings'].includes(key)?split(value):value;if(key==='id'&&config.overview_fields)config.overview_fields=config.overview_fields.map(id=>id===old?value:id);}}if(d.context)config.context[d.context]=e.target.checked;if(e.target.id==='reading-reasons')config.reading_plan.reason_choices=split(e.target.value);updateSummary();});
document.addEventListener('change',e=>{if(e.target.dataset.key==='type'){const item=values(e.target.dataset.kind)[+e.target.dataset.index];item.type=e.target.value;if(item.type!=='text')item.options??=[];render();}});
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{if(b.dataset.step)setStep(+b.dataset.step);if(b.dataset.add){const k=b.dataset.add;config[k]??=[];if(['categories','domains'].includes(k))config[k].push({name:'',description:'',terms:[],require_any:[],exclude_terms:[]});else if(k==='sections')config[k].push({id:nextId('section',config[k]),title:'',headings:[]});else{const f={id:nextId(k==='fields'?'field':'note',config[k]),title:'',type:'single',options:[],exclusive_options:[]};if(k==='fields')Object.assign(f,{group:'',hint:'',required:false,author:false,terms:[]});config[k].push(f);if(k==='fields'&&config.overview_fields)config.overview_fields.push(f.id);}render();$('#'+k).lastElementChild?.querySelector('input')?.focus();}if(b.dataset.remove){const arr=values(b.dataset.remove),removed=arr.splice(+b.dataset.index,1)[0];if(b.dataset.remove==='fields'&&config.overview_fields)config.overview_fields=config.overview_fields.filter(id=>id!==removed.id);render();}if(b.dataset.move){const a=config.reading_plan.groups,i=+b.dataset.move,j=i+(+b.dataset.direction);[a[i],a[j]]=[a[j],a[i]];render();}if(b.dataset.browse){browseTarget=b.dataset.browse;browseKind=b.dataset.kind;$('#use-folder').hidden=browseKind!=='folder';$('#browser').showModal();await browse($('#'+browseTarget).value||home);}if(b.dataset.filePath){if(b.dataset.directory==='true')await browse(b.dataset.filePath);else choosePath(b.dataset.filePath);}}catch(e){error(e);}});
$('#next').onclick=()=>setStep(step+1);$('#back').onclick=()=>setStep(step-1);$('#add-reading').onclick=()=>{config.reading_plan.groups.push({id:nextId('priority',config.reading_plan.groups),title:'',depth:'detailed',match:{}});render();};
$('#close-browser').onclick=()=>$('#browser').close();$('#browse-go').onclick=()=>browse($('#browse-path').value);$('#browse-path').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();browse(e.target.value);}};$('#browse-up').onclick=()=>browse($('#browse-up').dataset.path);$('#browse-home').onclick=()=>browse(home);$('#drive').onchange=e=>browse(e.target.value);$('#use-folder').onclick=()=>choosePath(folder);
$('#import-button').onclick=()=>$('#import-file').click();$('#import-file').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;const next=JSON.parse(await file.text());await api('/api/validate',{config:next});config=next;config.categories??=[];config.domains??=[];config.fields??=[];config.domain_notes??=[];for(const f of [...config.fields,...config.domain_notes])f.type??='text';config.reading_plan??={};config.reading_plan.groups??=[];config.reading_plan.reason_choices??=[];config.context??={};$('#project-name').value=config.name;render();notice('Settings imported. Choose sources and a new review folder; the original settings file is unchanged.');}catch(e){error(e);}finally{$('#import-file').value='';}};
$('#download-settings').onclick=async()=>{try{config.name=$('#project-name').value.trim();await api('/api/validate',{config});download(slug(config.name)+'.project.json',JSON.stringify(config,null,2)+'\n','application/json');notice('Settings downloaded. Keep this file to reuse your review scheme.');}catch(e){error(e);}};
$('#check').onclick=async()=>{try{cleanError();const r=await api(handoffProject?'/api/handoff-check':'/api/check',payload());notice(`Settings valid. ${r.records} papers will be prepared in a new review.`);}catch(e){error(e);}};
$('#create').onclick=async()=>{try{await run(handoffProject?'/api/handoff':'/api/create',payload());}catch(e){error(e);}};
$('#open-saved').onclick=()=>$('#resume').showModal();$('#close-resume').onclick=()=>$('#resume').close();$('#resume-go').onclick=async()=>{try{await run('/api/resume',{run:$('#resume-path').value});$('#resume').close();setStep(3);}catch(e){$('#resume-error').textContent=e.message;}};
$('#search-toggle').onclick=()=>$('#search-content').hidden=!$('#search-content').hidden;
$('#search-name').oninput=e=>{if(!$('#search-slug').dataset.edited)$('#search-slug').value=slug(e.target.value).replaceAll('_','-');};$('#search-slug').oninput=()=>$('#search-slug').dataset.edited='1';
$('#search-create').onclick=async()=>{try{await run('/api/search',{name:$('#search-name').value,slug:$('#search-slug').value});}catch(e){error(e);}};
$('#search-resume').onclick=async()=>{try{await run('/api/search',{project:$('#search-existing').value});}catch(e){error(e);}};
$('#search-handoff').onclick=()=>{handoffProject=$('#search-existing').value;if(!handoffProject)return;$('#csv-inputs').hidden=true;$('#handoff-inputs').hidden=false;$('#handoff-info').textContent='Included papers from: '+handoffProject;setStep(0);notice('Now configure labels and evidence fields for these included papers.');};
$('#cancel-handoff').onclick=()=>{handoffProject='';$('#csv-inputs').hidden=false;$('#handoff-inputs').hidden=true;updateSummary();};
api('/api/bootstrap').then(data=>{token=data.token;home=data.home;$('#parent-folder').value=data.projects;$('#csv-template').onclick=()=>download('records_template.csv',data.csv_template,'text/csv');if(data.search_projects){$('#search-tools').hidden=false;$('#search-existing').innerHTML='<option value="">Choose saved project…</option>'+data.search_projects.map(p=>`<option value="${esc(p.path)}">${esc(p.name)}</option>`).join('');}render();setStep(0);}).catch(error);
